apiVersion: v1
kind: Service
metadata:
  name: krb5-server
spec:
  selector:
    app: krb5-server
  ports:
  - name: kerberos
    port: 88
    targetPort: 88
  - name: kerberosu
    protocol: UDP
    port: 88
    targetPort: 88
  - name: kadmin
    port: 749
    targetPort: 749
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: krb5-conf
  labels:
    app: krb5-server
data:
  krb5.conf: |
    # Configuration snippets may be placed in this directory as well
    includedir /etc/krb5.conf.d/
    [logging]
    default = FILE:/var/log/krb5libs.log
    kdc = FILE:/var/log/krb5kdc.log
    admin_server = FILE:/var/log/kadmind.log

    [libdefaults]
    default_realm = DEFAULT.SVC.CLUSTER.LOCAL
    dns_lookup_realm = false
    dns_lookup_kdc = false

    [realms]
    DEFAULT.SVC.CLUSTER.LOCAL = {
        kdc = krb5-server.default.svc.cluster.local
        admin_server = krb5-server.default.svc.cluster.local
        default_domain = .default.svc.cluster.local
    }

    [domain_realm]
     default.svc.cluster.local = DEFAULT.SVC.CLUSTER.LOCAL
     .default.svc.cluster.local = DEFAULT.SVC.CLUSTER.LOCAL
  kdc.conf: |
    [kdcdefaults]
    kdc_ports = 88
    kdc_tcp_ports = 88
    spake_preauth_kdc_challenge = edwards25519

    [realms]
    DEFAULT.SVC.CLUSTER.LOCAL = {
        master_key_type = aes256-cts
        acl_file = /krb5-conf/kadm5.acl
        dict_file = /usr/share/dict/words
        admin_keytab = /var/kerberos/krb5kdc/kadm5.keytab
        supported_enctypes = aes256-cts:normal aes128-cts:normal arcfour-hmac:normal camellia256-cts:normal camellia128-cts:normal
    }
  kadm5.acl: |
    */admin@DEFAULT.SVC.CLUSTER.LOCAL *
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: krb5kdc-data
  labels:
    app: krb5-server
spec:
  storageClassName: rook-cephfs
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
---
apiVersion: v1
kind: Pod
metadata:
  name: krb5-server
  labels:
    app: krb5-server
spec:
  setHostnameAsFQDN: true
  #restartPolicy: Never
  containers:
    - name: krb5-server
      image: quay.io/spuiuk/krb5-server:latest
      ports:
        - containerPort: 88
          name: kerberos
          protocol: TCP
        - containerPort: 88
          name: kerberosu
          protocol: UDP
        - containerPort: 749
          name: kadmin
          protocol: TCP
      volumeMounts:
        - mountPath: "/krb5-conf"
          name: krb5-conf
        - mountPath: "/var/kerberos/krb5kdc"
          name: krb5kdc-data
      #command:
        #- "sleep"
        #- "36000"
  volumes:
    - name: krb5-conf
      configMap:
        name: krb5-conf
    - name: krb5kdc-data
      persistentVolumeClaim:
        claimName: krb5kdc-data

